# This is a template yaml for the processor
health_check_port: 8085
server_config:
  transaction_stream_config:
    indexer_grpc_data_service_address: "https://grpc.devnet.aptoslabs.com:443"
    auth_token: "aptoslabs_S2oG3GwzNWK_PBcesGHPStRQBuqoYbp2a72AWEtppwCMx"
    request_name_header: "events-processor"
    starting_version: 431944650  # Start from our first devnet deployment
  postgres_config:
    connection_string: postgresql://postgres:postgres@localhost:5432/sudo_indexer
